# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63lass.proto\x12\tmypackage\"3\n\x05\x43lass\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"\x15\n\x07\x43lassID\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\nAllClasses\x12!\n\x07\x63lasses\x18\x01 \x03(\x0b\x32\x10.mypackage.Class\"\x07\n\x05\x45mpty2\xe2\x01\n\x0c\x43lassService\x12\x38\n\rGetAllClasses\x12\x10.mypackage.Empty\x1a\x15.mypackage.AllClasses\x12\x30\n\x08\x41\x64\x64\x43lass\x12\x10.mypackage.Class\x1a\x12.mypackage.ClassID\x12\x31\n\tEditClass\x12\x10.mypackage.Class\x1a\x12.mypackage.ClassID\x12\x33\n\x0bRemoveClass\x12\x12.mypackage.ClassID\x1a\x10.mypackage.EmptyB \n\x10\x63om.example.grpcB\nClassProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'class_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.example.grpcB\nClassProtoP\001'
  _CLASS._serialized_start=26
  _CLASS._serialized_end=77
  _CLASSID._serialized_start=79
  _CLASSID._serialized_end=100
  _ALLCLASSES._serialized_start=102
  _ALLCLASSES._serialized_end=149
  _EMPTY._serialized_start=151
  _EMPTY._serialized_end=158
  _CLASSSERVICE._serialized_start=161
  _CLASSSERVICE._serialized_end=387
# @@protoc_insertion_point(module_scope)
